trigger:
- main

name: Deploy solution

variables:
  vmImageName: 'ubuntu-latest'

  azureServiceConnection: 'PiaSys Main Azure Subscription'
  resourceGroupName: 'bicep-demo'
  location: 'northeurope'
  templateFile: './first-sample.bicep'
pool:
  vmImage: $(vmImageName)

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureServiceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    useGlobalConfig: false
    inlineScript: |
      az --version
      az group create --name $(resourceGroupName) --location $(location)
      az deployment group create --resource-group $(resourceGroupName) --template-file $(templateFile) --parameters resourcesPrefix=$(RESOURCESPREFIX)